name: Deploy MERN App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install backend dependencies
        run: |
          cd backend
          sudo npm install

      - name: Build frontend
        run: |
          cd frontend
          sudo npm install
          sudo npm run build

      - name: Deploy to Server
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USER: ${{ secrets.SERVER_USER }}
          IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "$SSH_KEY" > private_key
          chmod 600 private_key
          sudo cp -r frontend/dist/* /var/www/html
          sudo cp -r backend/* var/www/backend
          ssh -i private_key $USER@$IP 'cd /var/www/backend && sudo npm i pm2 -g && pm2 start index js -f' # assuming pm2 is used for process management
